services:

  planocontadb:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04

  planocontahandson.api:
    image: ${DOCKER_REGISTRY-}planocontahandsonapi
    build:
      context: .
      dockerfile: src/PlanoContaHandsOn.API/Dockerfile

  prometheus:
    image: prom/prometheus:v3.5.0

  grafana:
    image: grafana/grafana-oss:12.1.0-ubuntu   

  jaeger:
    image: jaegertracing/jaeger:2.9.0 