// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanoContaHandsOn.Infrastructure.Data;

#nullable disable

namespace PlanoContaHandsOn.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanoContaHandsOn.Domain.Entities.PlanoConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceitaLancamento")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IdPai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdPai");

                    b.HasIndex("Nome", "Codigo");

                    b.ToTable("PlanoConta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8b512f4-9478-4222-811d-487b3b8a3e4e"),
                            AceitaLancamento = false,
                            Codigo = "1",
                            Nome = "Receitas",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("d6e1b2f8-2c39-4f7a-8f6a-3e21b1e9b8a1"),
                            AceitaLancamento = false,
                            Codigo = "2",
                            Nome = "Despesas",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("PlanoContaHandsOn.Domain.Entities.PlanoConta", b =>
                {
                    b.HasOne("PlanoContaHandsOn.Domain.Entities.PlanoConta", null)
                        .WithMany()
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
